default: &default
  adapter: postgresql
  host: localhost
  user: itssnihongo1
  password: itssnihongo1

development:
  <<: *default
  database: hotel_dev

test:
  <<: *default
  database: hotel_test

production:
  <<: *default
